apiVersion: v1
kind: Service
metadata:
  name: iris-service
spec:
  selector:
    app: iris-python
  ports:
  - protocol: "TCP"
    port: 5500
    targetPort: 5000
    nodePort: 30002
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-python
spec:
  selector:
    matchLabels:
      app: iris-python
  replicas: 1
  template:
    metadata:
      labels:
        app: iris-python
    spec:
      containers:
      - name: iris-python
        image: gouthamceast/iris-app-flask:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000